// VERSION 1.0.7
const fonts = [
    "ＭＳ ゴシック",
    "ＭＳ 明朝",
    "ＭＳ Ｐゴシック",
    "ＭＳ Ｐ明朝",
    "Osaka-Mono",
    "Osaka",
    "Hiragino Sans",
    "ヒラギノ角ゴシック",
    "游明朝",
    "游ゴシック",
    "Noto Sans Mono CJK JP",
    "Noto Sans JP",
    "Noto Serif JP",
    "Meiryo",
    "Meiryo UI",
    "MS UI Gothic",
    "Yu Gothic",
    "BIZ UDPゴシック",
    "BIZ UDP明朝",
    "いろは角クラシック",
    "源ノ明朝",
    "源柔ゴシック",
    "源柔ゴシックP",
    "源真ゴシック",
    "源真ゴシックP",
    "GN-キルゴUかなNA",
    "GN-キルゴUかなNB",
    "GN-キルゴUかなO",
    "IPA Pゴシック",
    "IPA P明朝",
    "JKゴシックL",
    "JKゴシックM",
    "Sawarabi Mincho",
    "Shippori Antique",
    "TT-JTCウインZ10P",
    "UD デジタル 教科書体 NK-B",
    "UD デジタル 教科書体 NK-R",
    "UD デジタル 教科書体 NP-B",
    "UD デジタル 教科書体 NP-R",
    "VL PGothic",
    "XANO明朝U32",
    "いろはマル",
    "こころ明朝体",
    "たぬき油性マジック",
    "はんなり明朝",
    "へた字",
    "ほにゃ字Re",
    "ゆるもじ",
    "りいてがきN",
    "りいポップ角",
    "梅ゴシック",
    "梅明朝",
    "梅Pゴシック",
    "梅P明朝",
    "不忘フェルトペン書体04",
    "HGPｺﾞｼｯｸE",
    "HGPｺﾞｼｯｸM",
    "HGP教科書体",
    "HGP行書体",
    "HGP創英角ｺﾞｼｯｸUB",
    "HGP創英角ﾎﾟｯﾌﾟ体",
    "HGP明朝B",
    "HGP明朝E",
    "HGSｺﾞｼｯｸE",
    "HGSｺﾞｼｯｸM",
    "HGS教科書体",
    "HGS行書体",
    "HGS創英角ｺﾞｼｯｸUB",
    "HGS創英角ﾎﾟｯﾌﾟ体",
    "HGS明朝B",
    "HGS明朝E",
    "HG丸ｺﾞｼｯｸM-PRO",
    "HG正楷書体-PRO",
    "RFナウ-GM",
    "RFナウ-MM",
    "RFPナウ-GM",
    "RFPナウ-MM",
    "Academy Engraved LET",
    "Adelle Sans Devanagari",
    "AkayaKanadaka",
    "AkayaTelivigala",
    "Al Bayan Plain",
    "Al Bayan",
    "Al Firat",
    "Al Khalil",
    "Al Nile",
    "Al Rafidain Al Fanni",
    "Al Rafidain",
    "Al Tarikh",
    "Algiers",
    "American Typewriter",
    "Andale Mono",
    "Annai MN",
    "Apple Braille Outline 6 Dot",
    "Apple Braille Outline 8 Dot",
    "Apple Braille Outline",
    "Apple Braille Pinpoint 6 Dot",
    "Apple Braille Pinpoint 8 Dot",
    "Apple Braille Pinpoint",
    "Apple Braille",
    "Apple Chancery",
    "Apple Color Emoji",
    "Apple LiGothic",
    "Apple LiSung",
    "Apple SD Gothic Neo UltraLight",
    "Apple SD Gothic Neo",
    "Apple Symbols",
    "AppleGothic",
    "AppleMyungjo",
    "Arial Black",
    "Arial Hebrew Scholar",
    "Arial Hebrew",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial Rounded MT",
    "Arial Unicode MS",
    "Arial",
    "Arima Koshi",
    "Arima Madurai Semi",
    "Arima Madurai",
    "Asphalt",
    "Athelas",
    "Avenir Next Condensed",
    "Avenir Next Demi",
    "Avenir Next Ultra",
    "Avenir Next",
    "Avenir Oblique",
    "Avenir Roman",
    "Avenir",
    "Ayuthaya",
    "BIZ UDGothic",
    "BIZ UDMincho",
    "BM DoHyeon OTF",
    "BM HANNA 11yrs old OTF",
    "BM HANNA Air OTF",
    "BM HANNA Pro OTF",
    "BM JUA OTF",
    "BM KIRANGHAERANG OTF",
    "BM YEONSUNG OTF",
    "Baghdad",
    "Bahnschrift",
    "Bai Jamjuree",
    "Balega",
    "Baloo 2",
    "Baloo Bhai 2",
    "Baloo Bhaijaan",
    "Baloo Bhaina 2",
    "Baloo Chettan 2",
    "Baloo Da 2",
    "Baloo Paaji 2",
    "Baloo Tamma 2",
    "Baloo Tammudu 2",
    "Baloo Thambi 2",
    "Bangla MN",
    "Bangla Sangam MN",
    "Bank Gothic",
    "Baoli SC",
    "Baoli TC",
    "Baskerville",
    "Basra",
    "Bebas Neue",
    "Beirut",
    "BiauKai",
    "BiauKaiHK",
    "BiauKaiTC",
    "Big Caslon",
    "Blackmoor LET Plain:2.0",
    "BlairMdITC TT",
    "Bodoni 72 Oldstyle",
    "Bodoni 72 Smallcaps",
    "Bodoni 72",
    "Bodoni Ornaments",
    "Bodoni SvtyTwo ITC TT",
    "Bodoni SvtyTwo ITC TTIta",
    "Book Antiqua",
    "Bookman Old Style",
    "Bordeaux Roman LET Plain",
    "Bradley Hand",
    "Braganza",
    "Brill Roman",
    "Brill",
    "Brush Script MT",
    "Calibri",
    "Cambay Devanagari Oblique",
    "Cambay Devanagari",
    "Cambria Math",
    "Cambria",
    "Candara",
    "Canela Deck",
    "Canela Text",
    "Canela",
    "Capitals",
    "Carlito",
    "Carrois Gothic SC",
    "Cascadia Code",
    "Cascadia Mono",
    "Catamaran",
    "Century Gothic",
    "Century Schoolbook",
    "Chakra Petch",
    "Chalkboard SE",
    "Chalkboard",
    "Chalkduster",
    "Charcoal CY",
    "Charm",
    "Charmonman",
    "Charter Roman",
    "Charter",
    "Cochin",
    "Comic Sans MS",
    "Coming Soon",
    "Consolas",
    "Constantia",
    "Copperplate",
    "Corbel",
    "Corsiva Hebrew",
    "Courier New",
    "Courier Oblique",
    "Courier",
    "Cutive Mono",
    "DB LCD Temp",
    "DFKaiShu-SB-Estd-BF",
    "DIN Alternate",
    "DIN Condensed",
    "DIN",
    "Damascus Semi",
    "Damascus",
    "Dancing Script",
    "Dash Practice",
    "Dash",
    "Dear Joe Four Small",
    "Dear Joe Four",
    "DecoType Naskh",
    "Devanagari MT",
    "Devanagari Sangam MN",
    "Didot",
    "Dijla",
    "Diwan Kufi",
    "Diwan Thuluth",
    "Domaine Display",
    "Droid Sans Fallback",
    "Droid Sans Mono",
    "Druk Super",
    "Druk Text",
    "Druk Wide",
    "Druk",
    "Ebrima",
    "Euphemia UCAS",
    "Fahkwang",
    "Fakt Slab Stencil Pro",
    "Farah",
    "Farisi",
    "Forgotten Futurist Shadow",
    "Forgotten Futurist",
    "Founders Grotesk Condensed",
    "Founders Grotesk Text",
    "Founders Grotesk",
    "Franklin Gothic Medium",
    "Futura",
    "GB18030 Bitmap",
    "Gabriola",
    "Gadugi",
    "Galvji Oblique",
    "Galvji",
    "Garamond",
    "Geeza Pro",
    "Geeza",
    "Geneva CY",
    "Geneva",
    "Georgia",
    "Gill Sans",
    "Gotu",
    "Grantha Sangam MN",
    "Graphik Compact",
    "Graphik",
    "Gujarati MT",
    "Gujarati Sangam MN",
    "GungSeo",
    "Gurmukhi MN",
    "Gurmukhi MT",
    "Gurmukhi Sangam MN",
    "Hannotate SC",
    "Hannotate TC",
    "HanziPen SC",
    "HanziPen TC",
    "HeadLineA",
    "Hei",
    "Heiti SC",
    "Heiti TC",
    "Helvetica CY Oblique",
    "Helvetica CY Plain",
    "Helvetica CY",
    "Helvetica CYOblique",
    "Helvetica Neue UltraLight",
    "Helvetica Neue",
    "Helvetica Oblique",
    "Helvetica",
    "Herculanum",
    "Hiragino Kaku Gothic Pro W3",
    "Hiragino Kaku Gothic Pro W6",
    "Hiragino Kaku Gothic ProN W3",
    "Hiragino Kaku Gothic ProN W6",
    "Hiragino Kaku Gothic Std W8",
    "Hiragino Kaku Gothic StdN W8",
    "Hiragino Maru Gothic Pro W4",
    "Hiragino Maru Gothic ProN W4",
    "Hiragino Mincho Pro W3",
    "Hiragino Mincho Pro W6",
    "Hiragino Mincho ProN W3",
    "Hiragino Mincho ProN W6",
    "Hiragino Sans CNS W3",
    "Hiragino Sans CNS W6",
    "Hiragino Sans GB W3",
    "Hiragino Sans GB W6",
    "Hiragino Sans TC W3",
    "Hiragino Sans TC W6",
    "Hiragino Sans W0",
    "Hiragino Sans W1",
    "Hiragino Sans W2",
    "Hiragino Sans W3",
    "Hiragino Sans W4",
    "Hiragino Sans W5",
    "Hiragino Sans W6",
    "Hiragino Sans W7",
    "Hiragino Sans W8",
    "Hiragino Sans W9",
    "Hoefler Text Ornaments",
    "Hoefler Text",
    "HoloLens MDL2 Assets",
    "Hopper Script",
    "Hubballi",
    "ITF Devanagari Demi",
    "ITF Devanagari Marathi Demi",
    "ITF Devanagari Marathi",
    "ITF Devanagari",
    "Impact",
    "InaiMathi",
    "Ink Free",
    "Iowan Old Style Roman",
    "Iowan Old Style Titling",
    "Iowan Old Style",
    "Jaini Purva",
    "Jaini",
    "Javanese Text",
    "Jazz LET Plain:1.0",
    "Journal Sans New Inline",
    "K2D",
    "Kai",
    "Kailasa",
    "Kaiti SC",
    "Kaiti TC",
    "Kannada MN",
    "Kannada Sangam MN",
    "Katari",
    "Kavivanar",
    "Kefa",
    "Khmer MN",
    "Khmer Sangam MN",
    "Kigelia Arabic",
    "Kigelia",
    "Klee",
    "KoHo",
    "Kodchasan",
    "Kohinoor Bangla",
    "Kohinoor Devanagari",
    "Kohinoor Gujarati",
    "Kohinoor Telugu",
    "Kokonor",
    "Koufi Abjadi",
    "Krub",
    "Krungthep",
    "KufiStandardGK",
    "Lahore Gurmukhi",
    "Laimoon",
    "Lantinghei SC",
    "Lantinghei TC",
    "Lao MN",
    "Lao Sangam MN",
    "Lava Devanagari",
    "Lava Kannada",
    "Lava Telugu",
    "Leelawadee UI",
    "LiHei Pro",
    "LiSong Pro",
    "Libian SC",
    "Libian TC",
    "LingWai SC",
    "LingWai TC",
    "Lucida Console",
    "Lucida Grande",
    "Lucida Sans Unicode",
    "Luminari",
    "M PLUS 1p",
    "MS Gothic",
    "MV Boli",
    "Maku",
    "Malayalam MN",
    "Malayalam Sangam MN",
    "Malgun Gothic",
    "Mali",
    "Marion",
    "Marker Felt Wide",
    "Marker Felt",
    "Marlett",
    "Menlo",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft YaHei",
    "Microsoft Yi Baiti",
    "MingLiU-ExtB",
    "Mishafi Gold",
    "Mishafi",
    "Modak",
    "Mona Lisa Solid ITC TT",
    "Monaco",
    "Mongolian Baiti",
    "Mshtakan Oblique",
    "Mshtakan",
    "MshtakanOblique",
    "Mukta Malar",
    "Mukta Vaani",
    "Mukta",
    "MuktaMahee",
    "Muna",
    "Myanmar MN",
    "Myanmar Sangam MN",
    "Myanmar Text",
    "Myriad Arabic",
    "Nadeem",
    "Nanum Brush Script",
    "Nanum Pen Script",
    "NanumGothic",
    "NanumMyeongjo",
    "New Peninim MT Inclined",
    "New Peninim MT",
    "Niramit",
    "Nirmala UI",
    "Nisan",
    "Nom Na Tong",
    "Noteworthy",
    "Noto Nastaliq Urdu",
    "Noto Sans Adlam",
    "Noto Sans Armenian",
    "Noto Sans Avestan",
    "Noto Sans Bamum",
    "Noto Sans Bassa Vah",
    "Noto Sans Batak",
    "Noto Sans Bhaiksuki",
    "Noto Sans Brahmi",
    "Noto Sans Buginese",
    "Noto Sans Buhid",
    "Noto Sans CJK JP",
    "Noto Sans CJK",
    "Noto Sans Canadian Aboriginal",
    "Noto Sans Carian",
    "Noto Sans Caucasian Albanian",
    "Noto Sans Chakma",
    "Noto Sans Cham",
    "Noto Sans Coptic",
    "Noto Sans Cuneiform",
    "Noto Sans Cypriot",
    "Noto Sans Duployan",
    "Noto Sans Egyptian Hieroglyphs",
    "Noto Sans Elbasan",
    "Noto Sans Glagolitic",
    "Noto Sans Gothic",
    "Noto Sans Gunjala Gondi",
    "Noto Sans Hanifi Rohingya",
    "Noto Sans Hanunoo",
    "Noto Sans Hatran",
    "Noto Sans Imperial Aramaic",
    "Noto Sans Inscriptional Pahlavi",
    "Noto Sans Inscriptional Parthian",
    "Noto Sans Javanese",
    "Noto Sans Kaithi",
    "Noto Sans Kannada",
    "Noto Sans Kayah Li",
    "Noto Sans Kharoshthi",
    "Noto Sans Khojki",
    "Noto Sans Khudawadi",
    "Noto Sans Lepcha",
    "Noto Sans Limbu",
    "Noto Sans Linear A",
    "Noto Sans Linear B",
    "Noto Sans Lisu",
    "Noto Sans Lycian",
    "Noto Sans Lydian",
    "Noto Sans Mahajani",
    "Noto Sans Mandaic",
    "Noto Sans Manichaean",
    "Noto Sans Marchen",
    "Noto Sans Masaram Gondi",
    "Noto Sans Meetei Mayek",
    "Noto Sans Mende Kikakui",
    "Noto Sans Meroitic",
    "Noto Sans Miao",
    "Noto Sans Modi",
    "Noto Sans Mongolian",
    "Noto Sans Mro",
    "Noto Sans Multani",
    "Noto Sans Myanmar",
    "Noto Sans NKo",
    "Noto Sans Nabataean",
    "Noto Sans New Tai Lue",
    "Noto Sans Newa",
    "Noto Sans Ol Chiki",
    "Noto Sans Old Hungarian",
    "Noto Sans Old North Arabian",
    "Noto Sans Old Permic",
    "Noto Sans Old Persian",
    "Noto Sans Old South Arabian",
    "Noto Sans Old Turkic",
    "Noto Sans Old",
    "Noto Sans Oriya",
    "Noto Sans Osage",
    "Noto Sans Osmanya",
    "Noto Sans Pahawh Hmong",
    "Noto Sans Palmyrene",
    "Noto Sans Pau Cin Hau",
    "Noto Sans PhagsPa",
    "Noto Sans Phoenician",
    "Noto Sans Psalter Pahlavi",
    "Noto Sans Rejang",
    "Noto Sans Samaritan",
    "Noto Sans Saurashtra",
    "Noto Sans Sharada",
    "Noto Sans Siddham",
    "Noto Sans Sora Sompeng",
    "Noto Sans Sundanese",
    "Noto Sans Syloti Nagri",
    "Noto Sans Syriac",
    "Noto Sans Tagalog",
    "Noto Sans Tagbanwa",
    "Noto Sans Tai Le",
    "Noto Sans Tai Tham",
    "Noto Sans Tai Viet",
    "Noto Sans Takri",
    "Noto Sans Thaana",
    "Noto Sans Tifinagh",
    "Noto Sans Tirhuta",
    "Noto Sans Ugaritic",
    "Noto Sans Vai",
    "Noto Sans Wancho",
    "Noto Sans Warang Citi",
    "Noto Sans Yi",
    "Noto Sans Zawgyi",
    "Noto Serif Ahom",
    "Noto Serif Balinese",
    "Noto Serif Hmong Nyiakeng",
    "Noto Serif Kannada",
    "Noto Serif Myanmar",
    "Noto Serif Yezidi",
    "Noto Serif",
    "November Bangla Traditional Compressed Hairline",
    "November Bangla Traditional Compressed",
    "November Bangla Traditional Hairline",
    "November Bangla Traditional",
    "October Compressed Devanagari Hairline",
    "October Compressed Devanagari",
    "October Compressed Gujarati Hairline",
    "October Compressed Gujarati",
    "October Compressed Gurmukhi Hairline",
    "October Compressed Gurmukhi",
    "October Compressed Kannada Hairline",
    "October Compressed Kannada",
    "October Compressed Meetei Mayek Hairline",
    "October Compressed Meetei Mayek",
    "October Compressed Odia Hairline",
    "October Compressed Odia",
    "October Compressed Ol Chiki Hairline",
    "October Compressed Ol Chiki",
    "October Compressed Tamil Hairline",
    "October Compressed Tamil",
    "October Compressed Telugu Hairline",
    "October Compressed Telugu",
    "October Condensed Devanagari",
    "October Condensed Tamil",
    "October Devanagari Hairline",
    "October Devanagari",
    "October Gujarati Hairline",
    "October Gujarati",
    "October Gurmukhi Hairline",
    "October Gurmukhi",
    "October Kannada Hairline",
    "October Kannada",
    "October Meetei Mayek Hairline",
    "October Meetei Mayek",
    "October Odia Hairline",
    "October Odia",
    "October Ol Chiki Hairline",
    "October Ol Chiki",
    "October Tamil Hairline",
    "October Tamil",
    "October Telugu Hairline",
    "October Telugu",
    "Optima ExtraBlack",
    "Optima",
    "Oriya MN",
    "Oriya Sangam MN",
    "Osaka",
    "Osaka-Mono",
    "Osaka-等幅",
    "PCMyungjo",
    "PSL Ornanong Pro Demibold Italic",
    "PSL Ornanong Pro",
    "PT Mono",
    "PT Sans Caption",
    "PT Sans Narrow",
    "PT Sans",
    "PT Serif Caption",
    "PT Serif",
    "Padyakke Expanded One",
    "Palatino Linotype",
    "Palatino",
    "Papyrus",
    "Party LET Plain",
    "Party LET",
    "Phosphate Inline",
    "Phosphate Solid",
    "PilGi",
    "PingFang HK",
    "PingFang MO",
    "PingFang SC",
    "PingFang TC",
    "Plantagenet Cherokee",
    "PortagoITC TT",
    "Princetown LET",
    "Produkt",
    "Proxima Nova It",
    "Proxima Nova",
    "Publico Headline Roman",
    "Publico Headline",
    "Publico Text Roman",
    "Publico Text",
    "Quotes Caps",
    "Quotes Script",
    "Raanana",
    "Raya",
    "Roboto",
    "Rockwell",
    "STFangsong",
    "STHeiti",
    "STIX Two Math",
    "STIX Two Text",
    "STIXGeneral-Bold",
    "STIXGeneral-BoldItalic",
    "STIXGeneral-Italic",
    "STIXGeneral-Regular",
    "STIXIntegralsD-Bold",
    "STIXIntegralsD-Regular",
    "STIXIntegralsSm-Bold",
    "STIXIntegralsSm-Regular",
    "STIXIntegralsUp-Bold",
    "STIXIntegralsUp-Regular",
    "STIXIntegralsUpD-Bold",
    "STIXIntegralsUpD-Regular",
    "STIXIntegralsUpSm-Bold",
    "STIXIntegralsUpSm-Regular",
    "STIXNonUnicode-Bold",
    "STIXNonUnicode-BoldItalic",
    "STIXNonUnicode-Italic",
    "STIXNonUnicode-Regular",
    "STIXSizeFiveSym-Regular",
    "STIXSizeFourSym-Bold",
    "STIXSizeFourSym-Regular",
    "STIXSizeOneSym-Bold",
    "STIXSizeOneSym-Regular",
    "STIXSizeThreeSym-Bold",
    "STIXSizeThreeSym-Regular",
    "STIXSizeTwoSym-Bold",
    "STIXSizeTwoSym-Regular",
    "STIXVariants-Bold",
    "STIXVariants-Regular",
    "STKaiti",
    "STSong",
    "STXihei",
    "Sama Devanagari",
    "Sama Gujarati",
    "Sama Gurmukhi",
    "Sama Kannada",
    "Sama Malayalam",
    "Sama Tamil",
    "San Francisco",
    "Sana",
    "Santa Fe LET Plain:1.0",
    "Sarabun",
    "Sathu",
    "Sauber Script",
    "Savoye LET Plain:1.0",
    "Savoye LET",
    "Scheme-Bold",
    "SchoolHouse Cursive B",
    "SchoolHouse Printed A",
    "Segoe Fluent Icons",
    "Segoe MDL2 Assets",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI Emoji",
    "Segoe UI Historic",
    "Segoe UI Symbol",
    "Segoe UI Variable",
    "Segoe UI",
    "Seravek",
    "Shobhika",
    "Shree Devanagari 714",
    "SignPainter-HouseScript",
    "Silom",
    "SimSong",
    "SimSun",
    "Sinhala MN",
    "Sinhala Sangam MN",
    "Sitka",
    "Skia Extended",
    "Skia",
    "Snell Roundhand",
    "Somer",
    "Songti SC",
    "Songti TC",
    "Source Han Sans",
    "Source Han Serif",
    "Spot Mono",
    "Srisakdi",
    "Stone Sans ITC TT",
    "Stone Sans Sem ITC TT Semi",
    "Stone Sans Sem ITC TT SemiIta",
    "Sukhumvit Set Semi",
    "Sukhumvit Set Text",
    "Sukhumvit Set",
    "Superclarendon",
    "Sylfaen",
    "Symbol",
    "Synchro LET",
    "Tahoma",
    "Tamil MN",
    "Tamil Sangam MN",
    "Telugu MN",
    "Telugu Sangam MN",
    "The Hand Serif",
    "Thonburi",
    "Times New Roman",
    "Times Roman",
    "Times",
    "Tiro Bangla",
    "Tiro Devanagari Hindi",
    "Tiro Devanagari Marathi",
    "Tiro Devanagari Sanskrit",
    "Tiro Gurmukhi",
    "Tiro Kannada",
    "Tiro Tamil",
    "Tiro Telugu",
    "Toppan Bunkyu Gothic",
    "Toppan Bunkyu Midashi Gothic",
    "Toppan Bunkyu Midashi Mincho",
    "Toppan Bunkyu Mincho",
    "Trattatello",
    "Trebuchet MS",
    "Tsukushi A Round Gothic",
    "Tsukushi B Round Gothic",
    "Tw Cen MT",
    "UNKNOWN",
    "Verdana",
    "Waseem",
    "Wawati SC",
    "Wawati TC",
    "Webdings",
    "Weibei SC",
    "Weibei TC",
    "Wingdings 2",
    "Wingdings 3",
    "Wingdings",
    "Xingkai SC",
    "Xingkai TC",
    "Yaziji",
    "Yu Gothic",
    "YuGothic",
    "YuKyokasho Yoko",
    "YuKyokasho",
    "YuMincho +36p Kana",
    "YuMincho",
    "Yuanti SC",
    "Yuanti TC",
    "Yuppy SC",
    "Yuppy TC",
    "Zapf Dingbats",
    "Zapfino",
    "Zawra",
    "ヒラギノ角ゴシック",
    "モトヤマルベリ",
    "凸版文久",
    "凸版文久明朝",
    "凸版文久見出し",
    "凸版文久見出し明朝",
    "游",
    "游教科書体 横用",
    "游教科書体",
    "游明朝体 +36",
    "游明朝体",
    "筑紫 A 丸",
    "筑紫 B 丸",
    "黒体 - 簡",
    "黒体 - 繁",
];
