const fonts = [
    "ＭＳ ゴシック",
    "ＭＳ 明朝",
    "ＭＳ Ｐゴシック",
    "ＭＳ Ｐ明朝",
    "Osaka-Mono",
    "Osaka",
    "Hiragino Sans",
    "ヒラギノ角ゴシック",
    "游明朝",
    "游ゴシック",
    "Noto Sans Mono CJK JP",
    "Noto Sans JP",
    "Noto Serif JP",
    "Meiryo",
    "Meiryo UI",
    "MS UI Gothic",
    "Yu Gothic",
    "BIZ UDPゴシック",
    "BIZ UDP明朝",
    "いろは角クラシック",
    "源ノ明朝",
    "源柔ゴシック",
    "源柔ゴシックP",
    "源真ゴシック",
    "源真ゴシックP",
    "GN-キルゴUかなNA",
    "GN-キルゴUかなNB",
    "GN-キルゴUかなO",
    "IPA Pゴシック",
    "IPA P明朝",
    "JKゴシックL",
    "JKゴシックM",
    "Sawarabi Mincho",
    "Shippori Antique",
    "TT-JTCウインZ10P",
    "UD デジタル 教科書体 NK-B",
    "UD デジタル 教科書体 NK-R",
    "UD デジタル 教科書体 NP-B",
    "UD デジタル 教科書体 NP-R",
    "VL PGothic",
    "XANO明朝U32",
    "いろはマル",
    "こころ明朝体",
    "たぬき油性マジック",
    "はんなり明朝",
    "へた字",
    "ほにゃ字Re",
    "ゆるもじ",
    "りいてがきN",
    "りいポップ角",
    "梅ゴシック",
    "梅明朝",
    "梅Pゴシック",
    "梅P明朝",
    "不忘フェルトペン書体04",
    "HGPｺﾞｼｯｸE",
    "HGPｺﾞｼｯｸM",
    "HGP教科書体",
    "HGP行書体",
    "HGP創英角ｺﾞｼｯｸUB",
    "HGP創英角ﾎﾟｯﾌﾟ体",
    "HGP明朝B",
    "HGP明朝E",
    "HGSｺﾞｼｯｸE",
    "HGSｺﾞｼｯｸM",
    "HGS教科書体",
    "HGS行書体",
    "HGS創英角ｺﾞｼｯｸUB",
    "HGS創英角ﾎﾟｯﾌﾟ体",
    "HGS明朝B",
    "HGS明朝E",
    "HG丸ｺﾞｼｯｸM-PRO",
    "HG正楷書体-PRO",
    "Arial",
    "Helvetica",
    "Times New Roman",
    "Courier New",
    "Comic Sans MS",
    "Impact",
    "Roboto",
    "Source Han Sans",
];
